import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'What is it',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="w-full h-auto">{children}</body>
      </html>
    </ClerkProvider>
  );
}
